// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amqbmovhbaubmcbjqrmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtcWJtb3ZoYmF1Ym1jYmpxcm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDA1NDgsImV4cCI6MjA3MTY3NjU0OH0.z0tPIl6F1lvQIwzD-nHqz-r8k4WJtC2sT6juV_vMxAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});